### ISSUE TITLE
Failed to render MD on homepage

### ISSUE THREAD

**Issue by Raidienaty** [agmath/agmath.github.io#1]
Hey AGMath!

Just wanted to let you know that you had some bad rendering of MD on your homepage. Please look at line 8:
`nbsp; &nbsp;email: a.gilbert1 [at] snhu [dot] edu <br/>`

Your `[at]` and `[dot]` will not load into any HTML format I'm aware of. Figured I'd point this out!

Thanks,
Raidienaty

**Comment by agmath** [comment]
Hey Jack — I had intended for them to render as they do…simply showing [at] and [dot] rather than the symbols. Hope all is well!
